/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-02-22 08:10:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../home/top.jsp", out, false);
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/employee/register.css\" />\n");
      out.write("<div class=\"grid-item\" id=\"side_menu\">\n");
      out.write("<h1>회원 등록</h1>\n");
      out.write("</div>\n");
      out.write("<div class=\"grid-item\" id=\"content\">\n");
      out.write("<form id=\"form\">\n");
      out.write("<div id=\"register-container\">\t\n");
      out.write("\t\t<div class=\"input-group\">\n");
      out.write("\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"basic-addon1\">아이디</span> <input\n");
      out.write("\t\t\t\ttype=\"text\" id=\"customerID\" name=\"customerID\" class=\"form-control\"\n");
      out.write("\t\t\t\tplaceholder=\"ID 입력\" aria-describedby=\"basic-addon1\" >\n");
      out.write("\t\t</div><br />\n");
      out.write("\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"basic-addon1\">회원 이름</span> <input\n");
      out.write("\t\t\t\ttype=\"text\" id=\"customerName\" name=\"customerName\"\n");
      out.write("\t\t\t\tclass=\"form-control\" placeholder=\"이름 입력\"\n");
      out.write("\t\t\t\taria-describedby=\"basic-addon1\">\n");
      out.write("\t\t</div><br />\n");
      out.write("\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"basic-addon1\">비밀번호</span> <input\n");
      out.write("\t\t\t\ttype=\"text\" id=\"password\" name=\"password\" class=\"form-control\"\n");
      out.write("\t\t\t\tplaceholder=\"비밀번호 입력\" aria-describedby=\"basic-addon1\">\n");
      out.write("\t\t</div><br />\n");
      out.write("\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"basic-addon1\">주민번호</span> <input\n");
      out.write("\t\t\t\ttype=\"text\" id=\"ssn\" name=\"ssn\" class=\"form-control\"\n");
      out.write("\t\t\t\tplaceholder=\"주민번호 입력\" aria-describedby=\"basic-addon1\">\n");
      out.write("\t\t</div><br />\n");
      out.write("\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"basic-addon1\">전화번호</span> <input\n");
      out.write("\t\t\t\ttype=\"text\" id=\"phone\" name=\"phone\" class=\"form-control\"\n");
      out.write("\t\t\t\tplaceholder=\"전화번호를 입력하시오\" aria-describedby=\"basic-addon1\">\n");
      out.write("\t\t</div><br />\n");
      out.write("\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"basic-addon1\">주소</span> <input\n");
      out.write("\t\t\t\ttype=\"text\" id=\"city\" name=\"city\" class=\"form-control\"\n");
      out.write("\t\t\t\tplaceholder=\"주소를 입력하시오\" aria-describedby=\"basic-addon1\">\n");
      out.write("\t\t</div><br />\n");
      out.write("\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"basic-addon1\">상세주소</span> <input\n");
      out.write("\t\t\t\ttype=\"text\" id=\"address\" name=\"address\" class=\"form-control\"\n");
      out.write("\t\t\t\tplaceholder=\"상세주소를 입력하시오\" aria-describedby=\"basic-addon1\">\n");
      out.write("\t\t</div><br />\n");
      out.write("\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t<span class=\"input-group-addon\" id=\"basic-addon1\">우편번호</span> <input\n");
      out.write("\t\t\t\ttype=\"text\" id=\"postal_Code\" name=\"postal_Code\" class=\"form-control\"\n");
      out.write("\t\t\t\tplaceholder=\"우편번호를 입력하시오\" aria-describedby=\"basic-addon1\">\n");
      out.write("\t\t</div><br /><br />\n");
      out.write("\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t<button type=\"button\" id=\"confirm_btn\" class=\"btn btn-default btn-lg\">\n");
      out.write("\t\t\t\t<span class=\"glyphicon glyphicon-upload\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t\t\t확인\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<button type=\"button\" id=\"cancel_btn\" class=\"btn btn-default btn-lg\">\n");
      out.write("\t\t\t\t<span class=\"glyphicon glyphicon-repeat\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t\t\t취소\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t<input type=\"hidden\" name=\"cmd\" value=\"signup\"/>\n");
      out.write("\t\t<input type=\"hidden\" name=\"page\" value=\"signin\"/>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</form>\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../home/bottom.jsp", out, false);
      out.write("\n");
      out.write("<script>\n");
      out.write("\t$('#confirm_btn').click(function() {\n");
      out.write("\t$('#form')\n");
      out.write("\t.attr('action', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer.do').submit();\n");
      out.write("\t\t\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$('#cancel_btn').click(function() {\n");
      out.write("\t\t\talert('취소버튼클릭!!');\n");
      out.write("\t\t});\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
